"""add star purchases

Revision ID: 0312f72d0c56
Revises: b7e5c3a8f1d2
Create Date: 2026-09-11 20:26:35.644520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.time

# revision identifiers, used by Alembic.
revision: str = '0312f72d0c56'
down_revision: Union[str, Sequence[str], None] = 'b7e5c3a8f1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('invoice_payload', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='starpurchasestatus'), nullable=False),
    sa.Column('telegram_payment_charge_id', sa.String(length=100), nullable=True),
    sa.Column('paid_at', app.core.time.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND telegram_payment_charge_id IS NULL AND paid_at IS NULL) OR (status = 'paid' AND telegram_payment_charge_id IS NOT NULL AND paid_at IS NOT NULL)", name='ck_star_purchase_paid_fields_match_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_payload'),
    sa.UniqueConstraint('telegram_payment_charge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('star_purchases')
    # ### end Alembic commands ###
