"""add admin grants and topup requests

Revision ID: 25b4fd9347e5
Revises: 5e2a8f14c9b3
Create Date: 2026-08-29 09:41:53.220965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.time

# revision identifiers, used by Alembic.
revision: str = '25b4fd9347e5'
down_revision: Union[str, Sequence[str], None] = '5e2a8f14c9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('topup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receipt_file_path', sa.String(length=500), nullable=False),
    sa.Column('requested_stars', sa.Integer(), nullable=False),
    sa.Column('star_rate_at_request', sa.Integer(), nullable=False),
    sa.Column('requested_toman_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='topupstatus'), nullable=False),
    sa.Column('final_toman_amount', sa.Integer(), nullable=True),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', app.core.time.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND final_toman_amount IS NULL AND transaction_reference IS NULL  AND rejection_reason IS NULL AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL) OR (status = 'approved' AND final_toman_amount IS NOT NULL AND transaction_reference IS NOT NULL  AND rejection_reason IS NULL AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL) OR (status = 'rejected' AND final_toman_amount IS NULL AND transaction_reference IS NULL  AND rejection_reason IS NOT NULL AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL)", name='ck_topup_review_fields_match_status'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_users_username'))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    # ### end Alembic commands ###

    # NOT autogenerated: SQLite's CHECK-constraint introspection doesn't
    # let Alembic detect that ck_topup_entries_have_no_transaction's
    # CONDITION TEXT changed (only added/removed constraints by name are
    # detected) when LedgerEntryType.TOPUP was added — see
    # app/models/credit_ledger.py. Without this, approving a real top-up
    # would violate the OLD constraint (which only recognizes
    # 'topup_dev_stub' as a transaction-less type) and fail with an
    # IntegrityError the first time anyone actually used it. SQLite has
    # no ALTER CONSTRAINT, so this rebuilds the table by hand — a plain
    # batch_alter_table here hit the same reflection issues documented
    # in the "make user username unique" migration, so this uses the
    # same manual create-copy-swap pattern that was proven to work there.
    op.execute(
        """
        CREATE TABLE credit_ledger_entries_new (
            id INTEGER NOT NULL,
            user_id INTEGER,
            amount_toman INTEGER NOT NULL,
            type VARCHAR(14) NOT NULL,
            transaction_id INTEGER,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            CONSTRAINT ck_commission_entries_have_no_user CHECK (
                (type = 'commission' AND user_id IS NULL) OR
                (type != 'commission' AND user_id IS NOT NULL)
            ),
            CONSTRAINT ck_topup_entries_have_no_transaction CHECK (
                (type IN ('topup_dev_stub', 'topup') AND transaction_id IS NULL) OR
                (type NOT IN ('topup_dev_stub', 'topup') AND transaction_id IS NOT NULL)
            ),
            FOREIGN KEY(user_id) REFERENCES users (id),
            FOREIGN KEY(transaction_id) REFERENCES transactions (id)
        )
        """
    )
    op.execute("INSERT INTO credit_ledger_entries_new SELECT * FROM credit_ledger_entries")
    op.execute("DROP TABLE credit_ledger_entries")
    op.execute("ALTER TABLE credit_ledger_entries_new RENAME TO credit_ledger_entries")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_users_username'), ['username'], unique=1)

    op.drop_table('topup_requests')
    op.drop_table('admin_grants')
    # ### end Alembic commands ###
