"""add optional birthday year

Revision ID: 732f56f522ee
Revises: 25b4fd9347e5
Create Date: 2026-08-30 21:09:33.359994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732f56f522ee'
down_revision: Union[str, Sequence[str], None] = '25b4fd9347e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Not left as the plain autogenerated batch_alter_table.add_column()
    # — that alone would add the column but leave the OLD
    # ck_birthday_both_or_neither constraint text in place (SQLite's
    # CHECK-constraint introspection only detects a constraint being
    # added/removed by NAME, not its condition text changing — the same
    # limitation documented in the "add admin grants" migration). Since
    # the constraint keeps its name here, autogenerate didn't flag it at
    # all. One raw rebuild does both the new column and the corrected
    # constraint together, instead of two separate full-table rebuilds.
    op.execute(
        """
        CREATE TABLE profiles_new (
            id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            bio VARCHAR(1000),
            location VARCHAR(200),
            interests JSON NOT NULL,
            is_trusted BOOLEAN DEFAULT 0 NOT NULL,
            birthday_month INTEGER,
            birthday_day INTEGER,
            birthday_year INTEGER,
            PRIMARY KEY (id),
            CONSTRAINT ck_birthday_both_or_neither CHECK (
                (birthday_month IS NULL AND birthday_day IS NULL AND birthday_year IS NULL) OR
                (birthday_month BETWEEN 1 AND 12 AND birthday_day BETWEEN 1 AND 31
                 AND (birthday_year IS NULL OR birthday_year BETWEEN 1900 AND 2100))
            ),
            FOREIGN KEY(user_id) REFERENCES users (id),
            UNIQUE (user_id)
        )
        """
    )
    op.execute(
        "INSERT INTO profiles_new "
        "(id, user_id, bio, location, interests, is_trusted, birthday_month, birthday_day) "
        "SELECT id, user_id, bio, location, interests, is_trusted, birthday_month, birthday_day "
        "FROM profiles"
    )
    op.execute("DROP TABLE profiles")
    op.execute("ALTER TABLE profiles_new RENAME TO profiles")


def downgrade() -> None:
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('birthday_year')
