"""baseline: current schema

Revision ID: baccd8850bb2
Revises: 
Create Date: 2026-08-26 17:38:23.492355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.time

# revision identifiers, used by Alembic.
revision: str = 'baccd8850bb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('joined_at', app.core.time.UTCDateTime(), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', name='userstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('audience_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='followstatus'), nullable=False),
    sa.Column('requested_at', app.core.time.UTCDateTime(), nullable=False),
    sa.Column('responded_at', app.core.time.UTCDateTime(), nullable=True),
    sa.CheckConstraint('follower_id != followee_id', name='ck_no_self_follow'),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followee_id', name='uq_follow_pair')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('chat', name='offerservicetype'), nullable=False),
    sa.Column('price_stars', sa.Integer(), nullable=False),
    sa.Column('display_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='offerstatus'), nullable=False),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('birthday_month', sa.Integer(), nullable=True),
    sa.Column('birthday_day', sa.Integer(), nullable=True),
    sa.CheckConstraint('(birthday_month IS NULL AND birthday_day IS NULL) OR (birthday_month BETWEEN 1 AND 12 AND birthday_day BETWEEN 1 AND 31)', name='ck_birthday_both_or_neither'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audience_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_at', app.core.time.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['audience_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('photo', 'short_video', name='contenttype'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('original_file_path', sa.String(length=500), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('price_stars', sa.Integer(), nullable=True),
    sa.Column('has_spoiler', sa.Boolean(), nullable=False),
    sa.Column('audience_type', sa.Enum('public', 'followers', 'user', 'group', name='contentaudience'), nullable=False),
    sa.Column('audience_user_id', sa.Integer(), nullable=True),
    sa.Column('audience_group_id', sa.Integer(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.CheckConstraint("(audience_type IN ('public', 'followers')  AND audience_user_id IS NULL AND audience_group_id IS NULL)OR (audience_type = 'user'  AND audience_user_id IS NOT NULL AND audience_group_id IS NULL)OR (audience_type = 'group'  AND audience_group_id IS NOT NULL AND audience_user_id IS NULL)", name='ck_audience_target_matches_type'),
    sa.CheckConstraint("(content_type = 'short_video' AND duration_seconds IS NOT NULL  AND duration_seconds > 0 AND duration_seconds <= 60) OR (content_type = 'photo' AND duration_seconds IS NULL)", name='ck_duration_matches_content_type'),
    sa.CheckConstraint('(is_paid AND price_stars IS NOT NULL) OR (NOT is_paid AND price_stars IS NULL)', name='ck_price_matches_is_paid'),
    sa.CheckConstraint('NOT is_paid OR has_spoiler', name='ck_paid_implies_spoiler'),
    sa.ForeignKeyConstraint(['audience_group_id'], ['audience_groups.id'], ),
    sa.ForeignKeyConstraint(['audience_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'cancelled', name='requeststatus'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.Column('responded_at', app.core.time.UTCDateTime(), nullable=True),
    sa.CheckConstraint("(status IN ('rejected', 'cancelled') AND reason IS NOT NULL) OR (status IN ('pending', 'accepted') AND reason IS NULL)", name='ck_reason_matches_status'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_open_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', app.core.time.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', app.core.time.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_content_purchase')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_like')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('chat_request', 'content_purchase', name='transactionkind'), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('gross_price_stars', sa.Integer(), nullable=False),
    sa.Column('commission_rate_percent', sa.Integer(), nullable=False),
    sa.Column('commission_stars', sa.Integer(), nullable=False),
    sa.Column('net_provider_stars', sa.Integer(), nullable=False),
    sa.Column('star_to_toman_rate', sa.Integer(), nullable=False),
    sa.Column('gross_price_toman', sa.Integer(), nullable=False),
    sa.Column('commission_toman', sa.Integer(), nullable=False),
    sa.Column('net_provider_toman', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='transactionstatus'), nullable=False),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.Column('disputed_at', app.core.time.UTCDateTime(), nullable=True),
    sa.CheckConstraint("(kind = 'chat_request' AND request_id IS NOT NULL AND content_id IS NULL) OR (kind = 'content_purchase' AND content_id IS NOT NULL AND request_id IS NULL)", name='ck_transaction_target_matches_kind'),
    sa.CheckConstraint('commission_stars + net_provider_stars = gross_price_stars', name='ck_star_split_sums_to_gross'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='chatsessionstatus'), nullable=False),
    sa.Column('opened_at', app.core.time.UTCDateTime(), nullable=False),
    sa.Column('closed_at', app.core.time.UTCDateTime(), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('credit_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount_toman', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('topup_dev_stub', 'spend', 'receive', 'commission', name='ledgerentrytype'), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.CheckConstraint("(type = 'commission' AND user_id IS NULL) OR (type != 'commission' AND user_id IS NOT NULL)", name='ck_commission_entries_have_no_user'),
    sa.CheckConstraint("(type = 'topup_dev_stub' AND transaction_id IS NULL) OR (type != 'topup_dev_stub' AND transaction_id IS NOT NULL)", name='ck_topup_entries_have_no_transaction'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('text', 'photo', 'video', 'voice', name='chatmessagetype'), nullable=False),
    sa.Column('text', sa.String(length=4000), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', app.core.time.UTCDateTime(), nullable=False),
    sa.CheckConstraint("(type = 'text' AND text IS NOT NULL AND file_path IS NULL AND duration_seconds IS NULL) OR (type = 'photo' AND file_path IS NOT NULL AND text IS NULL AND duration_seconds IS NULL) OR (type = 'video' AND file_path IS NOT NULL AND duration_seconds IS NOT NULL AND text IS NULL) OR (type = 'voice' AND file_path IS NULL AND duration_seconds IS NOT NULL AND text IS NULL)", name='ck_chat_message_fields_match_type'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_chat_session_id'))

    op.drop_table('chat_messages')
    op.drop_table('credit_ledger_entries')
    op.drop_table('chat_sessions')
    op.drop_table('transactions')
    op.drop_table('likes')
    op.drop_table('content_purchases')
    op.drop_table('content_open_logs')
    op.drop_table('requests')
    op.drop_table('contents')
    op.drop_table('audience_group_members')
    op.drop_table('profiles')
    op.drop_table('offers')
    op.drop_table('follows')
    op.drop_table('audience_groups')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
